### ISSUE TITLE
只能运行在linux平台？是否有计划windows版本

### ISSUE THREAD

**Issue by liuyunli** [Jacksgong/okcat#3]
只能运行在linux平台？是否有计划windows版本
谢谢！

**Comment by Jacksgong** [comment]
windows版本在python环境下应该也是可以的，有遇到什么问题吗？

比如说，在windows下通过`pip`进行安装，我查了下: [看这](https://stackoverflow.com/questions/29817447/how-to-run-pip-commands-from-cmd)
